# Generated by Django 3.1 on 2020-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('narrow_description', models.TextField()),
                ('time_place', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('tour_includes', models.CharField(max_length=255)),
                ('body2', models.TextField()),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('news_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('news_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('news_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
